name: example
description: A new Flutter project.
version: 1.0.0
author: Robby Rahmana <robbyrahmana79@gmail.com>
homepage: https://github.com/robbyrahmana/flutter_stack_card

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slider_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_slider_indicator:
    path: ../

flutter:
  uses-material-design: true
