name: flutter_slider_indicator
description: Slider Indicator Widget built in for flutter. Please press star in my repo if you like it. Thank you.
version: 0.2.0
author: Robby Rahmana <robbyrahmana79@gmail.com>
homepage: https://github.com/robbyrahmana/flutter_slider_indicator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter
